baseURL = 'https://shindy-dev.github.io/shindys-note/'
languageCode = 'ja'
defaultContentLanguage = "ja"
title = "Shindy's Note"
theme = "PaperMod"


enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
  disableXML = false
  minifyOutput = true

[params]
  env = "production"
  title = "Shindy's Note"
  description = "è¶£å‘³æ›¸ã„ãŸæŠ€è¡“ãƒ¡ãƒ¢ã§ã™ğŸ¹"
  keywords = ["Blog", "shindy", "Tech"]
  author = "shindy"
  # author = ["Me", "You"]
  images = ["/shindys-note/favicon.ico"]
  DateFormat = "2006å¹´1æœˆ2æ—¥"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    disableHLJS = true
  #  favicon = "<link / abs url>"
  #  favicon16x16 = "<link / abs url>"
  #  favicon32x32 = "<link / abs url>"
  #  apple_touch_icon = "<link / abs url>"
  #  safari_pinned_tab = "<link / abs url>"

  [params.label]
    text = "Shindy's Note"
    icon = "/shindys-note/favicon.ico"
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "Shindy's Note"
    subtitle = "æŠ€è¡“ãƒ¡ãƒ¢ã‚’å…¬é–‹ã—ã¦ã„ã¾ã™ğŸ¹"
    imageUrl = "/shindys-note/favicon.ico"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "shindy-icon"

    [[params.profileMode.buttons]]
      name = "Posts ğŸ“œ"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "Archive ğŸ“š"
      url = "archives"

    [[params.profileMode.buttons]]
      name = "Tags ğŸ·ï¸"
      url = "tags"

    [[params.profileMode.buttons]]
      name = "Search ğŸ”"
      url = "search"

  [params.homeInfoParams]
    Title = "Shindy's Note"
    Content = "è¶£å‘³æ›¸ã„ãŸæŠ€è¡“ãƒ¡ãƒ¢ã‚’å…¬é–‹ã—ã¦ã„ã¾ã™ğŸ¹"

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/shindy-dev"

    [[params.socialIcons]]
      name = "x"
      url = "https://x.com/ShindyDev"

    [[params.socialIcons]]
      name = "youtube"
      url = "https://www.youtube.com/@shindy-dev"

    [[params.socialIcons]]
      name = "kofi"
      url = "https://ko-fi.com/shindy_dev"


  [params.analytics.google]
    SiteVerificationTag = "$GOOGLE_ANALYTICS_ID"

  #[params.analytics.bing]
  #  SiteVerificationTag = "XYZabc"

  #[params.analytics.yandex]
  #  SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

  [params.editPost]
    URL = "https://github.com/shindy-dev/shindys-note/blob/master/content"
    Text = "Suggest Changes ğŸ“"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content", "tags"]

  [params.footer]
    text = "[åˆ©ç”¨è¦ç´„](/shindys-note/terms/)"
    hideCopyright = false

[outputs]
  home = ["HTML", "JSON", "RSS"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/Archives/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

  [[menu.main]]
    identifier = "repo"
    name = "Repo"
    url = "https://github.com/shindy-dev/shindys-note"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    lineNos = true
    # style = "monokai"
