name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master  # mainの場合はここを書き換える
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitattributes"
      - ".gitignore"
      - ".gitmodules"
      - ".github/FUNDING.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # テーマをサブモジュールにしてる場合

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'  # 好きなHugoバージョンに変更可
          extended: true           # SCSS/SASSをビルドするテーマの場合はtrueにしないとエラーになる
          
      - name: Build Hugo site
        run: |
          # PaperModCustomize の内容を PaperMod に上書きコピー
          rsync -a ./themes/PaperModCustomize/ ./themes/PaperMod/
          echo "=== PaperMod content ==="
          ls -R ./themes/PaperMod/
          
          # Google Analytics ID を設定
          sed -i "s/\$GOOGLE_ANALYTICS_ID/${GOOGLE_ANALYTICS_ID}/g" hugo.toml
          # Hugoのビルドを実行
          hugo --minify
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
